### ISSUE TITLE
Random disconnects from server

### ISSUE THREAD

**Issue by Damongirl** [Tarnadas/net64plus#29]
My friends and I were experiencing random disconnects from the server I was hosting last night, even I was disconnecting from it. It kept happening the entire time we played and net64 client would crash occasionally too after a connect.

**Comment by SuperToad64** [comment]
Yep, I have this issue as well. It is really annoying. It happens to me when I connect to the local server 127.0.0.1 and the disconnects are random. I made sure my settings were correct and I am using the default graphics plugin that came with SM64O 2.0. I have no idea what is causing this but this never happened in the previous 1.1.3 version of SM64O.

**Comment by SuperToad64** [comment]
So is there any reason why we are having random disconnects? I would like this solved.

**Comment by Damongirl** [comment]
Same. It's really frustrating to both me and my friends. Makes the experience less fun.

**Comment by Tarnadas** [comment]
There is a 5min afk timeout. There could eventually be a problem with that.
Any clue when the disconnect happens?

**Comment by Damongirl** [comment]
It just happens when we're playing. No one is afk when the disconnects happen.

**Comment by SuperToad64** [comment]
afk? What does that mean. It just happens randomly. even when all of us are playing. If it has a timeout function you should include a setting to turn that off for LAN players. That would solve the problem entirely.

**Comment by SuperToad64** [comment]
Oh ok. Yeah me and my friends are playing nonstop and it just disconnects. We are using Xbox One Windows Controllers if that makes a difference. We are not using the keyboard.

**Comment by Damongirl** [comment]
We're not using keyboards either. I'm using a Switch pro controller and my friend uses an Xbox One controller. Still the disconnects are pissing us off.

**Comment by Tarnadas** [comment]
Does the disconnect happen after exactly 5min? Is it only in a specific gamemode?

The afk timeout checks whether your x/y position has changed

**Comment by Damongirl** [comment]
It happens whenever we're moving around. So there shouldn't be any disconnecting when we're playing the game.

**Comment by SuperToad64** [comment]
Same for me. Just randomly disconnects. Then I will find one of my friends model stuck in place just blinking. I have to reconnect them for me to see their actual model, then the frozen one disappears. I think the afk timeout code is bugged. I think adding a setting to turn that part of the code off for LAN users would be the best solution. 

Because people connecting to online servers wouldn't have this problem. Multiplayer servers need the afk timeout code just in case someone quit the server and didn't close down Net64. I don't think it is needed for LAN play though.

**Comment by SuperToad64** [comment]
Cool! Did you finally find the cause of this weird glitch? I saw the commit you did: 
[net64plus-server:master] 1 new commit
73086de fix: Prevent disconnects caused by malfunction ... - Tarnadas

So will this be released in a new Net64+ version? Probably 2.0.2 I hope. Thanks for looking into this and solving it. I can't wait until the next update! :)

**Comment by Damongirl** [comment]
I hope so! Maybe we can make the afk timeout configurable. Really happy these random disconnects are potentially fixed.

**Comment by Damongirl** [comment]
Right? Been waiting for this update. Now I can sm64 seriously with my friends.

**Comment by Tarnadas** [comment]
It will be released in the server repository as a standalone download and with the next client update it will also be bundled in the download.

The Node version is already updated, but I still have to compile the exe for user servers and upload it. So some servers from the list are already updated and no longer have the problem
