### ISSUE TITLE
Other characters display death textures while you are dying

### ISSUE THREAD

**Issue by Dungeneer** [Tarnadas/net64plus#42]
As said in the title, when your in-game character dies, all other characters you see also display their death texture (X in eyes).

https://dungen.owns-an-apple.store/73cfc2ac.png (picture)

**Comment by SuperToad64** [comment]
Yeah, I have had this as well. I don't think it is an issue. This just happens because you are linking Super Mario 64 games together that were never designed to do so. Once one model has a texture animation all of them will as well. This happens also if you are picking up a box, bomb, or any other throw-able object. It will appear in other characters hands as well, it just happens. It is really noticeable when a bunch of people are fighting Bowser. You will see a bunch of spinning Bowsers, LOL! I don't think there is any way to fix this as it is part of how Net64+ works.

**Comment by DizzyThermal** [comment]
This is an artifact of shared memory.. Somethings are unique, but in a game like Super Mario 64 on a system like N64 - as @SuperToad64 said, some things will mirror your own player's status.

This will also happen if you AFK and Mario goes to sleep (other players eyes will change)

I'll leave it to net64plus developers to determine if this is feasible to fix -- likely not, definitely not priority

**Comment by Tarnadas** [comment]
This is something too low priority. If it becomes more relevant, this issue can be reopened
