### ISSUE TITLE
32 bit version

### ISSUE THREAD

**Issue by rhtghbf** [Tarnadas/net64plus#49]
not everyone has a 64 bit pc so when will come out a 32 bit version

**Comment by rhtghbf** [comment]
to make it more compaatible with everyone

**Comment by SuperToad64** [comment]
Tarnadas has specifically said multiple times that there will be **NO 32 BIT VERSION!** The reason for this is because most of the resources that run Net64+ need more memory to run so they have to take advantage of the 64-bit architecture. So I am sorry to say this but in order for you to use SM64O 1.2.1 you need to buy a computer that supports the 64-bit architecture. Please stop opening this issue, it has been covered on multiple occasions, Thank you.

**Comment by computernewb** [comment]
These days, it's extremely rare to have a computer that doesn't support 64-bits. If your computer is made after 2006 it very likely supports 64-bit. My suggestion is to simply install a 64-bit version of your current OS. If you don't want to back-up everything and reinstall you could use something like VirtualBox.

**Comment by sbmn** [comment]
@SuperToad64 It's actually because winprocess breaks on x32 clients. I'm sure if Net64 moved away from winprocess all would be fine and dandy. Sadly there isn't a replacement for winprocess that works on x32 or is finished.

**Comment by SuperToad64** [comment]
@sbmn Ah I see. But in any case this needs to stop being asked. It has already been answered on multiple occasions. There will be no 32-bit version, Tarnadas explicitly said this multiple times. We should pin this on discord if needed so people will stop asking about it. Because it is getting pretty annoying.

**Comment by ZiroGX2** [comment]
rhtghbf it's not a lie. In fact 32 bit processors are not being mass produced for laptop and desktop hardware except for certain situations. BTW a computer with a 64 bit processor can be bought for around 50-100 bucks.

**Comment by Benedani** [comment]
I'm not exactly sure why you would want to play any N64 games on a 32 bit processor. 64 bit is as old as 2003, and using a processor even from that era basically gives you an unusable machine. I'm surprised you can even get Super Mario 64 running with a 32 bit processor. (If you have a 64 bit processor, why even bother using a 32 bit OS? It just gives you a disadvantage pretty much everywhere.) It's like saying GTA 3 should be ported for 16-bit CPUs so it can run on MS-DOS. Yeah, not gonna happen.

**Comment by Tarnadas** [comment]
#27

**Comment by SuperToad64** [comment]
Exactly. So anyone else trying to re-open this issue again. Read this quote carefully from Tarnadas:

"32bit support won't be implemented, sorry.

There are dependencies which rely on 64bit and I cannot compile them to 32bit"

There you have it. Thanks Tarnadas! :+1:

**Comment by rhtghbf** [comment]
@benedani is not ridiculous a laptop uses a 32 bit procesor and it can run even mk9 at 60 fps with graphics maxed out

**Comment by rhtghbf** [comment]
@computernewb mi processor is an Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz, 2100 Mhz, 2 principal processors, 4 logic processors

P.S: english isn´t my principal language

**Comment by Tarnadas** [comment]
That's a 64bit CPU. Since you installed a 32bit OS, you're basically cutting your performance a lot
