### ISSUE TITLE
Mupen64

### ISSUE THREAD

**Issue by BGP19000** [Tarnadas/net64plus#84]
I have been trying to get mupen64 to work with net64+ for a while now. The closest I have got is renaming Mupen64.exe to Project64.exe and which makes it show up in the searching for emulator thing but doesn't ever say it is in the game so I can't use it. If anyone knows a way to get mupen64 to work it would be greatly appreciated as I would like to TAS the game.

**Comment by fancymelonub** [comment]
You.
Fucking.
Idiot.
Dude, you just wasted time instead of realizing to use the emulator that came in the download, which
is the only emulator that Net64+ can use. If you **really** want to use Mupen64 with Net64+/SM64O then downgrade to at least 1.3.1 (which is on the old clients channel in the Net64 Discord server) and choose Mupen64. Make sure to set your game to 8MB.

**Comment by Bigpro19000** [comment]
Yeah, it doesn't work. I have tried on all versions from 1.0-1.3.1hotfix

**Comment by Tarnadas** [comment]
Mupen64 won't be supported, because it does not have 16MB support.
See https://github.com/mupen64plus/mupen64plus-core/issues/524

**Comment by loper12** [comment]
mupen64plus/mupen64plus-core#623

**Comment by briancullinan** [comment]
> _No description provided._

I get it. I landed here thinking I could add multiplayer networking to GoldenEye.
